version: "3"

services:

  app_beacon_catcher:
    container_name: beacon_catcher_fpm
    build:
      context: ./..
      dockerfile: ./docker/beacon_catcher_fpm/Dockerfile
    image: beacon_catcher_fpm:0.0.2
    environment:
      - BASIC_AUTH_ENABLED=yes
      - BASIC_AUTH_USERNAME=brum
      - BASIC_AUTH_PASSWORD=83y3tV64VZR97dHM
    volumes:
      - ./../app:/usr/src/app
      - ./../beacons:/var/tmp/beacons
    # user: "1000:1000"

  webserver_beacon_catcher:
    container_name: beacon_catcher_nginx
    build:
      context: ./..
      dockerfile: ./docker/nginx/Dockerfile
    image: beacon_catcher_nginx:0.0.2
    ports:
      - 80:80
    volumes:
      - ./../app/public/:/usr/src/app